export class Product {
  name!: string;
  stock!: number;
  price!: number;
  image: any;
}

// Generated by https://quicktype.io

export interface ProductResponse {
  id: number;
  name: string;
  image: string;
  stock: number;
  price: number;
  createdAt: Date;
  updatedAt: Date;
}
